# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Blog
tagline:          'SangHun'
description:      ''
url:              http://parksanghun.github.io
baseurl:          http://parksanghun.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/parksanghun
