# Site settings
title: SangHun
email: sanghun1984@gmail.com
description:

# url info
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://parksanghun.github.io # the base hostname & protocol for your site
enforce_ssl: parksanghun.github.io

# sns info
twitter_username: parksanghun
github_username:  parksanghun
facebook_username: ""

# url change (/:year/:month/:day)
permalink: /:categories/:year/:month/:day/:title

# timezone
timezone: Asia/Seoul

# highlighter settings
# Build settings
#highlighter: rouge
#markdown: kramdown

#kramdown:
#  input: GFM
#  hard_wrap: false
#  auto_ids: false
#  auto_id_stripping: false
#  syntax_highlighter: rouge
#  parse_block_html: false
#  enable_coderay: false
#
#  coderay:
#    coderay_wrap: div
#    coderay_line_numbers: nil
#    coderay_tab_width: 4
#    coderay_bold_every: 10
#    coderay_css: class

# post separator
excerpt_separator: <!--more-->

# CSSls
sass:
  sass_dir: _sass

# collections
collections:
  solutions:
    output: false
    permalink: /:categories/:year/:month/:day/:title

# paging
paginate: 15
paginate_path: "/list/:num/"

# gems
gems:
  - jekyll-paginate

# plugins
# safe: true

# exclude
exclude: [Rakefile, README, Gemfile]