# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            SangHun
tagline:          'Blog'
description:      ''
url:
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/parksanghun
